on: [push]

name: CI

jobs:

  build-rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Cache cargo packages 💾
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust 🦀
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test projects 🧪
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build projects 🚧
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  build-docker:
    name: Docker containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: ["api", "cli"]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers 💾
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.bin }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bin }}-buildx-
      - name: Build 🔧
        uses: docker/build-push-action@v2
        with:
          file: docker/${{ matrix.bin }}.Dockerfile
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache 🚚
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
